# Numpy <hr style="border:2.5px solid #5c3ef2ff"></hr>

<b> Tristan John Fortaleza</b>
<br>Computer Engineer

In [1]:
#i imports and packages
import numpy as np
from scipy import stats
from statistics import multimode

# 1D Array

In [2]:
my_array = [1,2,3]

In [3]:
type(my_array)

list

In [4]:
my_array = np.array([1,2,3])

In [5]:
np.shape(my_array)

(3,)

# 2D Array

In [6]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])

In [7]:
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.shape(my_array)

(2, 3)

In [9]:
trans_array = my_array.T

In [10]:
trans_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [11]:
np.shape(trans_array)

(3, 2)

In [12]:
np.sum(trans_array, axis = 0)

array([ 6, 15])

In [13]:
np.sum(trans_array, axis = 1)

array([5, 7, 9])

# Measure of Central Tendency

In [14]:
resistance = np.array([
    [3,9.1,9.3,9.5,9.8,9.8,10.4,10.4,10.5,10.5,11], #Jaguar
    [9.1,9.1,9.1,9.2,9.2,9.9,9.9,10.1,10.8,11,20] #Panther
])

In [15]:
resistance

array([[ 3. ,  9.1,  9.3,  9.5,  9.8,  9.8, 10.4, 10.4, 10.5, 10.5, 11. ],
       [ 9.1,  9.1,  9.1,  9.2,  9.2,  9.9,  9.9, 10.1, 10.8, 11. , 20. ]])

In [16]:
np.mean(resistance, axis = 1)

array([ 9.39090909, 10.67272727])

In [17]:
np.mean(resistance, axis = 0)

array([ 6.05,  9.1 ,  9.2 ,  9.35,  9.5 ,  9.85, 10.15, 10.25, 10.65,
       10.75, 15.5 ])

In [18]:
np.nanmean(resistance, axis = 1)

array([ 9.39090909, 10.67272727])

In [19]:
jag_mean = np.nanmean(resistance, axis = 1)[0]
pan_mean = np.nanmean(resistance, axis = 1)[1]

print(f'Jaguar_mean = {jag_mean:.2f} omhs')
print(f'Panther_mean = {pan_mean:.2f} omhs')

Jaguar_mean = 9.39 omhs
Panther_mean = 10.67 omhs


In [20]:
np.nanmedian(resistance, axis = 1)

array([9.8, 9.9])

In [21]:
jag_mean = np.nanmedian(resistance, axis = 1)[0]
pan_mean = np.nanmedian(resistance, axis = 1)[1]

print(f'Jaguar_mean = {jag_mean:.2f} omhs')
print(f'Panther_mean = {pan_mean:.2f} omhs')

Jaguar_mean = 9.80 omhs
Panther_mean = 9.90 omhs


In [22]:
stats.mode(resistance, axis = 1)

ModeResult(mode=array([9.8, 9.1]), count=array([2, 3]))

In [23]:
my_array = [1,1,2,2,3,4,5]
multimode(my_array)

[1, 2]

In [24]:
jag_res = resistance[0]
print("Jaguar mode:")
for i in multimode(jag_res):
    print(f'{i} in ohms')

Jaguar mode:
9.8 in ohms
10.4 in ohms
10.5 in ohms


In [25]:
pan_res = resistance[1]
print("Panther mode:")
for i in multimode(pan_res):
    print(f'{i} in ohms')

Panther mode:
9.1 in ohms


# Measures of Variability

In [26]:
resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3.9, 8],
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1, np.nan]
])

resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3.9,  8. ],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [27]:
res_max = np.nanmax(resistance, axis=1)
res_min = np.nanmin(resistance, axis=1)

res_range = res_max - res_min
res_range

array([ 7.1, 10.9])

In [28]:
print(f'Jaguar_range = {res_range[0]:.2f} ohms')
print(f'Panther_range = {res_range[1]:.2f} ohms')

Jaguar_range = 7.10 ohms
Panther_range = 10.90 ohms


In [29]:
# 1st Quartile
res_Q1 = np.nanpercentile(resistance, 25, axis=1)
res_Q1

array([9.2  , 9.125])

In [30]:
# 2nd Quartile
res_Q2 = np.nanpercentile(resistance, 50, axis=1)
res_Q2

array([9.8 , 9.55])

In [31]:
# 3rd Quartile
res_Q3 = np.nanpercentile(resistance, 75, axis=1)
res_Q3

array([10.45 , 10.625])

In [32]:
# IQR
print(f'Jaguar IQR = {res_Q3[0] - res_Q1[0]:.2f} ohms')
print(f'Panther IQR = {res_Q3[1] - res_Q1[1]:.2f} ohms')

Jaguar IQR = 1.25 ohms
Panther IQR = 1.50 ohms


In [33]:
# Variance
res_var = np.nanvar(resistance, ddof=1, axis=1)
res_var

array([ 3.96163636, 11.08277778])

In [34]:
print(f'Jaguar Variance = {res_var[0]:.2f} ohms')
print(f'Panther Variance = {res_var[1]:.2f} ohms')

Jaguar Variance = 3.96 ohms
Panther Variance = 11.08 ohms


In [35]:
# Standard Deviation
res_std = np.nanstd(resistance, ddof=1, axis=1)
res_std

array([1.99038598, 3.32908062])

In [36]:
print(f'Jaguar Standard Deviation = {res_std[0]:.2f} ohms')
print(f'Panther Standard Deviation = {res_std[1]:.2f} ohms')

Jaguar Standard Deviation = 1.99 ohms
Panther Standard Deviation = 3.33 ohms
