# Numpy <hr style="border:2.5px solid #5c3ef2ff"></hr>

<b> Tristan John Fortaleza</b>
<br>Computer Engineer

In [7]:
#i imports and packages
import numpy as np

# 1D Array

In [8]:
my_array = [1,2,3]

In [11]:
type(my_array)

numpy.ndarray

In [10]:
my_array = np.array([1,2,3])

In [12]:
np.shape(my_array)

(3,)

# 2D Array

In [45]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])

In [46]:
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.shape(my_array)

(2, 3)

In [48]:
trans_array = my_array.T

In [49]:
trans_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [50]:
np.shape(trans_array)

(3, 2)

In [51]:
np.sum(trans_array, axis = 0)

array([ 6, 15])

In [52]:
np.sum(trans_array, axis = 1)

array([5, 7, 9])

# Measure of Central Tendency

In [53]:
resistance = np.array([
    [3,9.1,9.3,9.5,9.8,9.8,10.4,10.4,10.5,10.5,11], #Jaguar
    [9.1,9.1,9.1,9.2,9.2,9.9,9.9,10.1,10.8,11,20] #Panther
])

In [54]:
resistance

array([[ 3. ,  9.1,  9.3,  9.5,  9.8,  9.8, 10.4, 10.4, 10.5, 10.5, 11. ],
       [ 9.1,  9.1,  9.1,  9.2,  9.2,  9.9,  9.9, 10.1, 10.8, 11. , 20. ]])

In [60]:
np.mean(resistance, axis = 1)

array([ 9.39090909, 10.67272727])